USE EverwellCardiacDB
GO;

SELECT TOP 10 *
FROM AdmissionData;
--------------------------
/* Data Cleaning */
--------------------------

--Creating view from the CleanData
CREATE OR ALTER VIEW vw_AdmissionData AS
--Creating CleanData(CTE) to extract non-duplicate data
WITH CleanData AS(
SELECT *,
	--Identifying duplicate data using Dup_no generated by window function
	ROW_NUMBER() OVER(PARTITION BY MRD_No,D_O_A,D_O_D ORDER BY MRD_No) Dup_No
FROM AdmissionData
)
--Selecting non-duplicate data
SELECT *
FROM CleanData
WHERE Dup_No = 1 AND MRD_No IS NOT NULL;

